In [2]:
import numpy as np
import torch

In [4]:
torch.cuda.is_available()

False

In [5]:
some_data = [[1,2],[3,4]]
type(some_data)

list

In [6]:
np.array(some_data)

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(some_data)

array([[1, 2],
       [3, 4]])

In [10]:
some_data = torch.tensor(some_data)
type(some_data)

/var/folders/jk/w8lkkz7n40s81208_5_qd5_80000gn/T/ipykernel_58403/2640947224.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  some_data = torch.tensor(some_data)


torch.Tensor

In [11]:
some_data.dtype

torch.int64

In [12]:
numpy_array = np.random.rand(3,4)
numpy_array

array([[0.22646161, 0.33413031, 0.26739775, 0.1320735 ],
       [0.81613091, 0.32394343, 0.36392009, 0.35500144],
       [0.67763887, 0.78434728, 0.61058448, 0.63424727]])

In [13]:
t_array = torch.from_numpy(numpy_array)

In [14]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
my_tensor = torch.rand(3,4)

In [18]:
my_tensor.dtype

torch.float32

In [19]:
my_tensor.device

device(type='cpu')

In [21]:
my_tensor[:, 1:3]

tensor([[0.3273, 0.8003],
        [0.7720, 0.1194],
        [0.6197, 0.2575]])

In [22]:
my_tensor.mul(my_tensor)

tensor([[0.1720, 0.1071, 0.6405, 0.8091],
        [0.7238, 0.5959, 0.0142, 0.0184],
        [0.3624, 0.3841, 0.0663, 0.0595]])

In [23]:
my_tensor * my_tensor

tensor([[0.1720, 0.1071, 0.6405, 0.8091],
        [0.7238, 0.5959, 0.0142, 0.0184],
        [0.3624, 0.3841, 0.0663, 0.0595]])

In [24]:
my_tensor.matmul(my_tensor.T)

tensor([[1.7286, 0.8230, 0.8779],
        [0.8230, 1.3524, 1.0544],
        [0.8779, 1.0544, 0.8722]])

In [25]:
torch.matmul(my_tensor, my_tensor.T)

tensor([[1.7286, 0.8230, 0.8779],
        [0.8230, 1.3524, 1.0544],
        [0.8779, 1.0544, 0.8722]])

In [26]:
my_tensor @ my_tensor.T

tensor([[1.7286, 0.8230, 0.8779],
        [0.8230, 1.3524, 1.0544],
        [0.8779, 1.0544, 0.8722]])

In [28]:
my_tensor.sum(axis=1)

tensor([2.4417, 1.8778, 1.7231])

In [29]:
my_tensor.sum(axis=0)

tensor([1.8674, 1.7189, 1.1772, 1.2791])

In [30]:
torch.max(my_tensor)

tensor(0.8995)

In [31]:
torch.min(my_tensor)

tensor(0.1194)

In [33]:
torch.cat([my_tensor, my_tensor])

tensor([[0.4147, 0.3273, 0.8003, 0.8995],
        [0.8508, 0.7720, 0.1194, 0.1357],
        [0.6020, 0.6197, 0.2575, 0.2438],
        [0.4147, 0.3273, 0.8003, 0.8995],
        [0.8508, 0.7720, 0.1194, 0.1357],
        [0.6020, 0.6197, 0.2575, 0.2438]])

In [34]:
torch.cat([my_tensor, my_tensor], axis=1)

tensor([[0.4147, 0.3273, 0.8003, 0.8995, 0.4147, 0.3273, 0.8003, 0.8995],
        [0.8508, 0.7720, 0.1194, 0.1357, 0.8508, 0.7720, 0.1194, 0.1357],
        [0.6020, 0.6197, 0.2575, 0.2438, 0.6020, 0.6197, 0.2575, 0.2438]])

In [35]:
torch.cat([my_tensor, my_tensor], dim=1)

tensor([[0.4147, 0.3273, 0.8003, 0.8995, 0.4147, 0.3273, 0.8003, 0.8995],
        [0.8508, 0.7720, 0.1194, 0.1357, 0.8508, 0.7720, 0.1194, 0.1357],
        [0.6020, 0.6197, 0.2575, 0.2438, 0.6020, 0.6197, 0.2575, 0.2438]])

In [36]:
torch.nn.functional.softmax(my_tensor, dim=1)

tensor([[0.1996, 0.1829, 0.2935, 0.3241],
        [0.3455, 0.3193, 0.1663, 0.1690],
        [0.2919, 0.2972, 0.2069, 0.2041]])

In [37]:
torch.sum(torch.nn.functional.softmax(my_tensor, dim=1), dim=1)

tensor([1., 1., 1.])

In [38]:
my_tensor.size()

torch.Size([3, 4])

In [39]:
my_tensor.size(0)

3

In [40]:
my_tensor.size(1)

4

In [41]:
my_tensor.size(-1)

4

In [42]:
# 10 batch size
# 3 channels
# size of image
img_tensor = torch.rand(10, 3, 128, 128)

In [43]:
img_tensor.size()

torch.Size([10, 3, 128, 128])

In [44]:
my_tensor.clip(0.2, 0.8)

tensor([[0.4147, 0.3273, 0.8000, 0.8000],
        [0.8000, 0.7720, 0.2000, 0.2000],
        [0.6020, 0.6197, 0.2575, 0.2438]])

In [45]:
my_tensor.detach().numpy()

array([[0.41469365, 0.32725096, 0.8003015 , 0.8994921 ],
       [0.8507653 , 0.77196324, 0.11936009, 0.13571936],
       [0.60198313, 0.6197321 , 0.25750208, 0.24384695]], dtype=float32)