In [1]:
import torch

In [2]:
a  = torch.tensor([5.], requires_grad=True)
b  = torch.tensor([6.], requires_grad=True)
a,b

(tensor([5.], requires_grad=True), tensor([6.], requires_grad=True))

In [3]:
y = a**3 -b**2
y

tensor([89.], grad_fn=<SubBackward0>)

### dy/da = 3a**2 = 3 * 5 * 5 = 75
### dy/db = -2*b = -2 * 6 = -12


In [4]:
y.backward()

In [5]:
a.grad, b.grad

(tensor([75.]), tensor([-12.]))

In [6]:
W = torch.rand(10, 1, requires_grad=True)
b = torch.rand(1, requires_grad=True)

In [7]:
X = torch.rand(1, 10)

In [8]:
Y = torch.matmul(X, W) + b

In [9]:
loss = 1 - Y

In [10]:
Y

tensor([[2.5194]], grad_fn=<AddBackward0>)

In [11]:
loss

tensor([[-1.5194]], grad_fn=<RsubBackward1>)

In [12]:
loss.backward()

In [16]:
W.grad


tensor([[-0.7367],
        [-0.1883],
        [-0.2666],
        [-0.0145],
        [-0.7832],
        [-0.3539],
        [-0.2202],
        [-0.9452],
        [-0.5049],
        [-0.2421]])

In [17]:
learning_rate = 0.001
with torch.no_grad():
    W = W - learning_rate * W.grad.data
W

tensor([[0.2654],
        [0.4952],
        [0.1007],
        [0.7022],
        [0.0141],
        [0.7584],
        [0.4153],
        [0.7351],
        [0.3453],
        [0.1696]])

In [18]:
W.grad = None